config/routes.rb
Rails.application.routes.draw do
  resources :bugs, path_names: {edit: "edit/:edit_type/:project_id"}
  resources :projects
  namespace :functionality do
    resources :users, path_names: {new: "new/:creator_id/:project_id"}
  end
  devise_for :users
  get "/user" => "main#index", :as => :user_root
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :bugs
  has_and_belongs_to_many :users
  validates :title, presence: true
  \
  attribute :title, :text, default: ""
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @bugs=@project.bugs
  end

  # GET /projects/new
  def new
    @project = Project.new
    authorize @project
  end

  # GET /projects/1/edit
  def edit
    @invalid_users = @project.users.where.not(role: :manager)
    @valid_users = User.where.not(role: :manager)- @invalid_users
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(title: params[:project][:title])
    authorize @project
    @project.users << current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    if params[:project][:new_users]!= "" then
      @project.users << User.find(params[:project][:new_users])
    end
    if params[:project][:remove_users] != "" then
      @project.users.delete(User.find(params[:project][:remove_users]))
    end
    respond_to do |format|
      if @project.update(title: params[:project][:title])
        format.html { redirect_to projects_url, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  private
  def set_project
    @project=Project.find(params[:id])
    authorize @project
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.permit(:id, :title, :new_users, :remove_users)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_editform.html.erb
<%= form_with(model: @project) do |form| %>
  <%= form.label  :title %><br />
  <%= form.text_field :title%><br />
  <%= form.label "Add Users"%><br />
  <%= form.collection_select :new_users, @valid_users, :id, :username, include_blank: true %><br />
  <%= form.label "Remove Users"%><br />
  <%= form.collection_select :remove_users, @invalid_users, :id, :username, include_blank: true %><br />
  <% if @project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <%= form.label  :title %><br />
  <%= form.text_field :title%>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "editform", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>





<% if current_user.manager? %>
  <h1><%= link_to "Create New Project", new_project_path %></h1><br />
  <% @projects.each do |project| %>
    <% if project.users.exists?(current_user.id)%>
      <ul>
        <h2><li><%= project.title%></li></h2>
        <li>
          <%= link_to "Add or Remove a User", edit_project_path(:id => project.id) %>
        </li>
        <li>
          <%= button_to "Delete Project", project_path(:id => project.id), method: :delete, class: "btn btn-dark"%>
        </li>
      </ul>
    <% end %>
  <% end %>
<% elsif current_user.developer?%>
  <% @projects.each do |project| %>
    <% if project.users.exists?(current_user.id)%>
      <%= link_to "#{project.title}", project_path(:id => project.id) %>
    <% end %>
  <% end %>
<% else %>
  <ul>
  <% @projects.each do |project| %>
    <% if project.users.exists?(current_user.id)%>
      <li><%= project.title %></li>
    <% end %>
  <% end %>
  </ul>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<div>
  <%= link_to "Create New Bug", new_bug_path(:creator_id => current_user.id,:project_id => @project.id) %><br />
  <% if @bugs then %>
    <% @bugs.each do|bug| %>
      <% if bug.types_status == "new" or bug.types_status == "started" then%>
        <ol>
          <li><%= bug.creator %></li>
          <% if  !bug.solver.nil? %>
            <li><%= bug.solver %></li>
          <% else %>
            <li><%= "No Solver Yet" %>
          <% end %>
          <li><%= bug.title %></li>
          <li><%= bug.project %></li>
          <li><%= bug.deadline %></li>
          <li><%= bug.bug_type %></li>
          <li><%= bug.types_status %></li>
          <% if bug.image.attached? then%>
            <li><%= link_to "View Screenshot", rails_blob_url(bug.image), target: :_blank%></li>
          <% end %>
        </ol>
      <% end %>
      <% if bug.types_status == "new" then %>
        <%= link_to "Edit_Status", edit_bug_path(:id => bug.id, :edit_type => 1, :project_id => @project.id)%><br /><br /><br />
      <% elsif bug.types_status == "started" %>
        <%= link_to "Edit_Status", edit_bug_path(:id => bug.id, :edit_type => 2, :project_id => @project.id)%><br /><br /><br />
      <% else %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>