config/routes.rb
Rails.application.routes.draw do
  resources :bugs, path_names: {edit: "edit/:edit_type/:project_id"}
  resources :projects
  namespace :functionality do
    resources :users, path_names: {new: "new/:creator_id/:project_id"}
  end
  devise_for :users
  get "/user" => "main#index", :as => :user_root
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main#index"
end

app/models/bug.rb
class Bug < ApplicationRecord
  has_one_attached :image
  belongs_to :project
  belongs_to :creator, class_name:"User"
  belongs_to :solver, class_name:"User", :optional => true
  attribute :title, :text, default: ""
  validates :title, :types_status, :bug_type, :deadline, presence: true
  validates :title, uniqueness: {case_sensitive: false}
  validate :acceptable_image
  def acceptable_image
    return unless image.attached?
    acceptable_types = ["image/gif", "image/png"]
    unless acceptable_types.include?(image.content_type)
      errors.add(:image, "must be png or gif")
    end
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: %i[ show edit update destroy ]
  before_action :bug_expired, only: %i[ show edit update destroy ]

  # GET /bugs or /bugs.json
  def index
    @bugs = Bug.all
  end

  # GET /bugs/1 or /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
    authorize @bug
    @creator = params[:creator_id]
    @project= params[:project_id]
  end

  # GET /bugs/1/edit
  def edit
    @edit_type=params[:edit_type]
    @bug = Bug.find(params[:id])
    @project = Project.find(params[:project_id])
    if @bug.bug_type == "Bug" then
      @final_status = "Resolved"
    else
      @final_status = "Completed"
    end
  end

  # POST /bugs or /bugs.json
  def create
    @bug = Bug.new(
      title: params[:bug][:title],
      deadline: params[:bug][:deadline],
      image: params[:bug][:image],
      bug_type: params[:bug][:bug_type],
      types_status: params[:bug][:types_status]
    )
    authorize @bug
    Project.find(params[:bug][:project_id]).bugs <<@bug
    User.find(params[:bug][:creator]).created_bugs <<@bug
    respond_to do |format|
      if @bug.save
        format.html { redirect_to project_path(:id => params[:bug][:project_id]), notice: "Bug was successfully created." }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1 or /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(types_status: params[:bug][:types_status])
        format.html { redirect_to project_path(:id => params[:bug][:project_id]), notice: "Bug was successfully updated." }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1 or /bugs/1.json
  def destroy
    @bug.destroy

    respond_to do |format|
      format.html { redirect_to bugs_url, notice: "Bug was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
      authorize @bug
    end

    def bug_expired
      @curr = Bug.find(params[:id])
      if (@curr.deadline> Date.today) or (@curr.types_status != "new" and @curr.types_status != "started")then
        @curr.destroy
        respond_to do |format|
          format.html { redirect_to bugs_url, notice: "Bug was successfully destroyed." }
          format.json { head :no_content }
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def bug_params
      params.require(:bug).permit(:creator, :title, :deadline, :bug_type, :image, :types_status, :project_id)
    end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_bug.html.erb
z<div id="<%= dom_id bug %>">
</div>

app/views/bugs/_form.html.erb
<%= form_with model: bug do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :deadline %><br>
    <%= form.date_field :deadline, min: Date.today %>
  </div>
  <div>
    <%= form.label :bug_type %><br>
    <%= form.select :bug_type, ["Bug", "Feature"], :selected => "Bug" %>
  </div>
  <div>
  <%= form.hidden_field :types_status, value: "new" %>
  <%= form.hidden_field :creator, value: "#{@creator}" %>
  <%= form.hidden_field :project_id, value: "#{@project}" %>
  <div>
    <%= form.file_field :image %>
  </div>

  <% if bug.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
        <% bug.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h1>Editing bug</h1>
<div>
  <% if @edit_type == "1"%>
    <%= form_with(model: @bug) do |form| %>
      <div>
        <%= form.label "Choose the status" %>
        <%= form.select :types_status, ["new", "started", @final_status], :selected => "new" %>
        <%= form.hidden_field :project_id, value: "#{@project.id}" %>
      </div>
      <div>
        <%= form.submit %>
      </div>
    <% end %>
  <% else %>
    <%= form_with(model: @bug) do |form| %>
      <div>
        <%= form.label "Choose the status" %>
        <%= form.select :types_status, ["started", @final_status], :selected => "started"  %>
        <%= form.hidden_field :project_id, value: "#{@project.id}" %>
      </div>
      <div>
        <%= form.submit %>
      </div>
    <% end %>
  <% end %>
</div>

<br>

<div>
  <%= link_to "Go back to Bugs", @project %>
</div>

app/views/bugs/index.html.erb
<h1>Bugs</h1>

<div id="bugs">
  <% @bugs.each do |bug| %>
    <%= render "bug", bug: bug %>
    <p>
      <%= link_to "Show this bug", bug %>
    </p>
  <% end %>
</div>

<%= link_to "New bug", new_bug_path %>

app/views/bugs/new.html.erb
<h1>New bug</h1>

<%= render "form", bug: @bug %>

<br>

<div>
  <%= link_to "Back to bugs", bugs_path %>
</div>

app/views/bugs/show.html.erb
<%= render @bug %>

<div>
  <%= link_to "Edit this bug", edit_bug_path(@bug) %> |
  <%= link_to "Back to bugs", bugs_path %>

  <%= button_to "Destroy this bug", @bug, method: :delete %>
</div>